### ISSUE TITLE
JSON Stream logs are 404s

### ISSUE THREAD

**Issue by Fingel** [lsst-uk/lasair#244]
Hello,

It seems that recently the JSON formatted stream logs have been returning 404s. A few examples:

https://lasair-iris.roe.ac.uk/lasair/static/streams/lasair_2AllnucleartransientsandTDEcandidates
https://lasair-iris.roe.ac.uk/lasair/static/streams/lasair_2SN-likecandidates

**Comment by RoyWilliams** [comment]
Austin
Fixed now. Thanks for pointing this out.
Roy

**Comment by Fingel** [comment]
Hi @RoyWilliams, I'm still having this issue with a few streams. In particular Yael's that we would like to start using.
https://lasair-iris.roe.ac.uk/lasair/static/streams/lasair_165NewTDEsEA
https://lasair-iris.roe.ac.uk/lasair/static/streams/lasair_165NewTDEs

**Comment by RoyWilliams** [comment]
Sorry about that Austin. Should be fixed now.
Roy

**Comment by Fingel** [comment]
This issue appears to be back. 
https://lasair-iris.roe.ac.uk/streams/lasair_165NewTDEsEA/
